-- WARNING: This script will DELETE ALL DATA from the database
-- It preserves table structure (migrations) but removes all records
-- Make sure you have a backup before running this!

-- Disable foreign key checks temporarily
ALTER TABLE IF EXISTS "Message" DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Notification" DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Like" DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Comment" DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Post" DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Friend" DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "User" DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Account" DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Session" DISABLE TRIGGER ALL;

-- Delete all data from tables (order matters due to FK constraints)
TRUNCATE TABLE "Message" CASCADE;
TRUNCATE TABLE "Notification" CASCADE;
TRUNCATE TABLE "Like" CASCADE;
TRUNCATE TABLE "Comment" CASCADE;
TRUNCATE TABLE "Post" CASCADE;
TRUNCATE TABLE "Friend" CASCADE;
TRUNCATE TABLE "Account" CASCADE;
TRUNCATE TABLE "Session" CASCADE;
TRUNCATE TABLE "VerificationToken" CASCADE;
TRUNCATE TABLE "User" CASCADE;

-- Re-enable foreign key checks
ALTER TABLE IF EXISTS "User" ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Session" ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Account" ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Friend" ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Post" ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Comment" ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Like" ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Notification" ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS "Message" ENABLE TRIGGER ALL;

-- Reset auto-increment sequences
ALTER SEQUENCE IF EXISTS "User_id_seq" RESTART WITH 1;
ALTER SEQUENCE IF EXISTS "Post_id_seq" RESTART WITH 1;
ALTER SEQUENCE IF EXISTS "Comment_id_seq" RESTART WITH 1;
ALTER SEQUENCE IF EXISTS "Message_id_seq" RESTART WITH 1;
ALTER SEQUENCE IF EXISTS "Notification_id_seq" RESTART WITH 1;
ALTER SEQUENCE IF EXISTS "Friend_id_seq" RESTART WITH 1;
ALTER SEQUENCE IF EXISTS "Like_id_seq" RESTART WITH 1;

-- Confirm cleanup completed
SELECT 'Database cleanup completed successfully!' as status;
