-- Script de nettoyage des données fictives
-- À exécuter avec une connexion PostgreSQL admin

-- Désactiver les contraintes de clé étrangère temporairement
ALTER TABLE IF EXISTS message_reactions DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS messages DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS story_reactions DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS story_views DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS stories DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS reactions DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS shares DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS likes DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS post_media DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS posts DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS comments DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_post_media DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_posts DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS group_post_media DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS group_posts DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_admins DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_invites DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_members DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS pages DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS group_members DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS groups DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS friendships DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS notifications DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS sessions DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS accounts DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS users DISABLE TRIGGER ALL;

-- Supprimer les données dans l'ordre inverse des dépendances
TRUNCATE TABLE message_reactions CASCADE;
TRUNCATE TABLE messages CASCADE;
TRUNCATE TABLE story_reactions CASCADE;
TRUNCATE TABLE story_views CASCADE;
TRUNCATE TABLE stories CASCADE;
TRUNCATE TABLE reactions CASCADE;
TRUNCATE TABLE shares CASCADE;
TRUNCATE TABLE likes CASCADE;
TRUNCATE TABLE post_media CASCADE;
TRUNCATE TABLE posts CASCADE;
TRUNCATE TABLE comments CASCADE;
TRUNCATE TABLE page_post_media CASCADE;
TRUNCATE TABLE page_posts CASCADE;
TRUNCATE TABLE group_post_media CASCADE;
TRUNCATE TABLE group_posts CASCADE;
TRUNCATE TABLE page_admins CASCADE;
TRUNCATE TABLE page_invites CASCADE;
TRUNCATE TABLE page_members CASCADE;
TRUNCATE TABLE pages CASCADE;
TRUNCATE TABLE group_members CASCADE;
TRUNCATE TABLE groups CASCADE;
TRUNCATE TABLE friendships CASCADE;
TRUNCATE TABLE notifications CASCADE;
TRUNCATE TABLE sessions CASCADE;
TRUNCATE TABLE accounts CASCADE;
TRUNCATE TABLE verification_tokens CASCADE;
TRUNCATE TABLE users CASCADE;

-- Réactiver les triggers
ALTER TABLE IF EXISTS users ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS verification_tokens ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS accounts ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS sessions ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS notifications ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS friendships ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS groups ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS group_members ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS pages ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_members ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_invites ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_admins ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS group_posts ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS group_post_media ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_posts ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_post_media ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS comments ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS posts ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS post_media ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS likes ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS shares ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS reactions ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS stories ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS story_views ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS story_reactions ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS messages ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS message_reactions ENABLE TRIGGER ALL;
