-- Nettoyer les données sans supprimer les tables
-- Exécuter en tant qu'admin PostgreSQL ou propriétaire des tables

BEGIN;

-- Désactiver temporairement les contraintes FK
ALTER TABLE IF EXISTS message_reactions DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS messages DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS story_reactions DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS story_views DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS stories DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS reactions DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS shares DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS likes DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS post_media DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS comments DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS posts DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS notifications DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS friendships DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS group_post_media DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS group_posts DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS group_members DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS groups DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_post_media DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_posts DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_admins DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_invites DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_members DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS pages DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS sessions DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS accounts DISABLE TRIGGER ALL;
ALTER TABLE IF EXISTS users DISABLE TRIGGER ALL;

-- Supprimer tous les enregistrements
DELETE FROM message_reactions;
DELETE FROM messages;
DELETE FROM story_reactions;
DELETE FROM story_views;
DELETE FROM stories;
DELETE FROM reactions;
DELETE FROM shares;
DELETE FROM likes;
DELETE FROM post_media;
DELETE FROM comments;
DELETE FROM posts;
DELETE FROM notifications;
DELETE FROM friendships;
DELETE FROM group_post_media;
DELETE FROM group_posts;
DELETE FROM group_members;
DELETE FROM groups;
DELETE FROM page_post_media;
DELETE FROM page_posts;
DELETE FROM page_admins;
DELETE FROM page_invites;
DELETE FROM page_members;
DELETE FROM pages;
DELETE FROM sessions;
DELETE FROM accounts;
DELETE FROM verification_tokens;
DELETE FROM users;

-- Réinitialiser les séquences auto-increment
ALTER SEQUENCE IF EXISTS message_reactions_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS messages_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS story_reactions_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS story_views_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS stories_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS reactions_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS shares_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS likes_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS post_media_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS comments_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS posts_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS notifications_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS friendships_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS group_post_media_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS group_posts_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS group_members_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS groups_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS page_post_media_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS page_posts_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS page_admins_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS page_invites_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS page_members_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS pages_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS sessions_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS accounts_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS verification_tokens_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS users_id_seq RESTART WITH 1;

-- Réactiver les triggers
ALTER TABLE IF EXISTS users ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS verification_tokens ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS accounts ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS sessions ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS pages ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_members ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_invites ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_admins ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS groups ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS group_members ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS group_posts ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS group_post_media ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS posts ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS post_media ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS comments ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS likes ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS shares ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS reactions ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS stories ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS story_views ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS story_reactions ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS messages ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS message_reactions ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS notifications ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS friendships ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_posts ENABLE TRIGGER ALL;
ALTER TABLE IF EXISTS page_post_media ENABLE TRIGGER ALL;

COMMIT;

-- Résumé
SELECT 'Nettoyage terminé avec succès!' as "Status";
